### ISSUE TITLE
rctmon is not starting

### ISSUE THREAD

**Issue by matzeruegge** [svalouch/rctmon#36]
I have upgraded my linux to Ubuntu 24.04.1 LTS. Now I have problems to restart rctmon again.
After the installation of "git+https://github.com/svalouch/rctmon" in a venv I receive the following error:

`rctmon-venv) matze@minix:~$ rctmon --debug -c /etc/rctmon.yml daemon

Traceback (most recent call last):
  File "/home/matze/rctmon-venv/bin/rctmon", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/rctmon/cli.py", line 50, in daemon
    settings = RctMonConfig(**ctx.obj['CONFIG'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matze/rctmon-venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for RctMonConfig
mqtt
  Field required [type=missing, input_value={'device': {'host': 'HF-A...andlers': ['console']}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
`
Any help is very welcome.

Kind regards 
Matthias

**Comment by matzeruegge** [comment]
After reading the error message multiple times I notices the 4 chars mqtt. So after adding mqtt configuration. rctmon is running again.
